from . import service_desk_reply_wizard
from . import service_desk_merge_wizard
from . import service_desk_mass_update_wizard
from . import service_desk_create_lead_wizard
from . import service_desk_create_sale_wizard
from . import service_desk_create_purchase_wizard
from . import service_desk_create_invoice_wizard
from . import service_desk_create_task_wizard
from . import service_desk_create_repair_wizard
from . import service_desk_whatsapp_send_wizard
from . import service_desk_end_ticket_wizard
from . import service_desk_custom_tab_wizard
from . import service_desk_custom_field_wizard
from . import service_desk_sticky_note_wizard
