from . import service_desk_ai
from . import service_desk_alarm
from . import service_desk_team_skill
from . import service_desk_team
from . import service_desk_stage
from . import service_desk_category
from . import service_desk_tag
from . import service_desk_priority
from . import service_desk_ticket_type
from . import service_desk_ticket_subject_type
from . import service_desk_sla
from . import service_desk_stage_log
from . import service_desk_ticket_rating
from . import service_desk_support_contract
from . import service_desk_customer_hour_package
from . import service_desk_auto_followup
from . import service_desk_sticky_note
from . import mail_mail
from . import mail_template
from . import service_desk_knowledge
from . import service_desk_custom_field
from . import service_desk_whatsapp
from . import service_desk_ticket_bridge_mixin
from . import service_desk_ticket
from . import service_desk_demo_data
from . import service_desk_ticket_analysis
from . import service_desk_config
from . import res_partner
from . import res_users
from . import crm_lead
from . import sale_order
from . import purchase_order
from . import account_move
from . import project_task
from . import account_analytic_line
from . import repair_order
from . import ir_attachment
